spring.application.name=PokemonSystem
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=1612
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=PokemonDB;encrypt=false
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true